# Generated by Django 4.0.3 on 2022-05-19 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streeter', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='shop',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='street',
            options={'ordering': ['id']},
        ),
    ]
