# Generated by Django 4.0.3 on 2022-05-26 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streeter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='close_time',
            field=models.TimeField(verbose_name='Время закрытия'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='open_time',
            field=models.TimeField(verbose_name='Время открытия'),
        ),
    ]
