# Generated by Django 4.0.3 on 2022-05-21 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streeter', '0002_alter_city_options_alter_shop_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='hidden_id',
            field=models.IntegerField(blank=True, default=0, verbose_name='id из kladr'),
        ),
    ]
