# Generated by Django 4.0.3 on 2022-05-21 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streeter', '0003_city_hidden_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='hidden_id',
        ),
    ]
